name: Thermal Daemon Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build cmake unzip

    - name: Cache Android NDK
      id: ndk-cache
      uses: actions/cache@v4
      with:
        path: android-ndk
        key: android-ndk-r26d-${{ runner.os }}
        restore-keys: |
          android-ndk-r26d-

    - name: Download Android NDK
      if: steps.ndk-cache.outputs.cache-hit != 'true'
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
        unzip android-ndk-r26d-linux.zip
        mv android-ndk-r26d android-ndk

    - name: Configure CMake
      run: |
        cmake -G Ninja \
          -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/android-ndk/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-31 \
          -B build

    - name: Build project
      run: cmake --build build

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: mi_thermald
        path: build/mi_thermald
        retention-days: 7
